# Generated by Django 6.1.1 on 2026-09-21 16:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apiApp', '0005_alter_category_slug'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='profle_picture_url',
            new_name='profile_picture_url',
        ),
    ]
